var menuTreeObject ={
  "nodes":[
    {"name":"Play","group":1,"fixed":true},
    {"name":"Scores","group":1,"fixed":true},
    {"name":"Instructions","group":1,"fixed":true},
    {"name":"Credits","group":1,"fixed":true},
    
    {"name":"Boy","group":3}, 
    {"name":"Girl","group":4},
    {"name":"Boy","group":3}, 
    {"name":"Girl","group":4},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Girl","group":4},
    
    {"name":"Girl","group":4},
    {"name":"Boy","group":3}, 
    {"name":"Girl","group":4},
    {"name":"Boy","group":3}, 
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Boy","group":4},
    
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Heart","group":2},
    {"name":"Boy","group":3},
    {"name":"Boy","group":3},
    {"name":"Boy","group":3},
    {"name":"Boy","group":3},
    {"name":"Boy","group":3}, 
    {"name":"Boy","group":3}, 
    {"name":"Girl","group":4},
    {"name":"Girl","group":4},
    {"name":"Girl","group":4},
    {"name":"Girl","group":4},
    {"name":"Girl","group":4},
    {"name":"Girl","group":4},
    
  ],
  "links":[
    {"source":0,"target":1,"value":5},
    {"source":1,"target":2,"value":5},
    {"source":2,"target":3,"value":5},
    
    {"source":0,"target":4,"value":5},
    {"source":0,"target":5,"value":5},
    {"source":1,"target":5,"value":5},
    {"source":1,"target":6,"value":5},
    {"source":2,"target":6,"value":5},
    {"source":2,"target":7,"value":5},
    {"source":3,"target":7,"value":5},
    
    {"source":4,"target":8,"value":5},
    {"source":5,"target":8,"value":5},
    {"source":5,"target":9,"value":5},
    {"source":6,"target":9,"value":5},
    {"source":6,"target":10,"value":5},
    {"source":7,"target":10,"value":5},
    
    {"source":8,"target":11,"value":5},
    {"source":8,"target":12,"value":5},
    {"source":9,"target":12,"value":5},
    
    {"source":10,"target":12,"value":5},
    {"source":12,"target":11,"value":5},
    {"source":4,"target":11,"value":5},
    
    
    {"source":0,"target":13,"value":5},
    {"source":0,"target":14,"value":5},
    {"source":1,"target":14,"value":5},
    {"source":1,"target":15,"value":5},
    {"source":2,"target":15,"value":5},
    {"source":2,"target":16,"value":5},
    {"source":3,"target":16,"value":5},
    
    {"source":13,"target":17,"value":5},
    {"source":14,"target":17,"value":5},
    {"source":14,"target":18,"value":5},
    {"source":15,"target":18,"value":5},
    {"source":15,"target":19,"value":5},
    {"source":16,"target":19,"value":5},
    
    {"source":17,"target":20,"value":5},
    {"source":17,"target":21,"value":5},
    {"source":18,"target":21,"value":5},
    
    {"source":19,"target":21,"value":5},
    {"source":20,"target":21,"value":5},
    {"source":20,"target":13,"value":5},
    
    {"source":0,"target":8,"value":5},
    {"source":0,"target":17,"value":5}
  ]
}